FROM ghcr.io/llnl/radiuss:cuda-12-8-ubuntu-24.04
LABEL maintainer="bramwell1@llnl.gov"
ARG branch=develop

USER serac
COPY ./scripts/docker /home/scripts
RUN /home/scripts/setup-docker.sh "+cuda+shared cuda_arch=70 %gcc_14"
