FROM ghcr.io/llnl/radiuss:gcc-14-ubuntu-24.04
LABEL maintainer="bramwell1@llnl.gov"
ARG branch=develop
ENV spec="~devtools~enzyme %gcc_14"

SHELL ["/bin/bash", "-c"]
RUN sudo apt-get update -y
RUN sudo apt-get install gettext gfortran-$(gcc -dumpversion) libopenblas-dev \
                         lsb-release lua5.2 lua5.2-dev mpich ssh -fy

# Remove flags from mpich
RUN sudo sed -i "s/ -flto=auto//g" /usr/bin/mpicxx.mpich
RUN sudo sed -i "s/ -flto=auto//g" /usr/bin/mpicc.mpich
RUN sudo sed -i "s/ -flto=auto//g" /usr/bin/mpifort.mpich
RUN sudo sed -i "s/ -ffat-lto-objects//g" /usr/bin/mpicxx.mpich
RUN sudo sed -i "s/ -ffat-lto-objects//g" /usr/bin/mpicc.mpich
RUN sudo sed -i "s/ -ffat-lto-objects//g" /usr/bin/mpifort.mpich
RUN sudo sed -i "s/ -fallow-invalid-boz//g" /usr/bin/mpifort.mpich
RUN sudo sed -i "s/ -fallow-argument-mismatch//g" /usr/bin/mpifort.mpich

RUN sudo useradd -m -s /bin/bash -G sudo serac
WORKDIR "/home/serac"
USER serac

RUN git clone --recursive --branch $branch --single-branch --depth 1 https://github.com/LLNL/serac.git serac_repo

WORKDIR "/home/serac/serac_repo"
RUN ./scripts/docker/setup-serac.sh
