FROM ghcr.io/llnl/radiuss:clang-19-ubuntu-24.04
LABEL maintainer="bramwell1@llnl.gov"
ARG branch=develop

USER serac
COPY ./scripts/docker /home/scripts
RUN /home/scripts/setup-docker.sh "+shared %clang_19"
