FROM ghcr.io/llnl/radiuss:gcc-14-ubuntu-24.04
LABEL maintainer="bramwell1@llnl.gov"
ARG branch=develop
ENV spec="%gcc_14"

SHELL ["/bin/bash", "-c"]
RUN sudo apt-get update -y
RUN sudo apt-get install gettext gfortran-$(gcc -dumpversion) libomp-dev libopenblas-dev \
                         lsb-release lua5.2 lua5.2-dev mpich ssh -fy

# Install devtool-related packages
# NOTE: Skipping this can significantly save disk space
RUN if [[ "$spec" != *~devtools* ]]; then \
      sudo apt-get install graphviz python3-sphinx texlive-full -fy \
      sudo wget https://github.com/doxygen/doxygen/releases/download/Release_1_9_8/doxygen-1.9.8.linux.bin.tar.gz \
      sudo tar -xf doxygen-1.9.8.linux.bin.tar.gz \
      cd doxygen-1.9.8 && sudo make && sudo make install && doxygen --version \
    fi

# Remove flags from mpich
RUN sudo sed -i "s/ -flto=auto//g" /usr/bin/mpicxx.mpich
RUN sudo sed -i "s/ -flto=auto//g" /usr/bin/mpicc.mpich
RUN sudo sed -i "s/ -flto=auto//g" /usr/bin/mpifort.mpich
RUN sudo sed -i "s/ -ffat-lto-objects//g" /usr/bin/mpicxx.mpich
RUN sudo sed -i "s/ -ffat-lto-objects//g" /usr/bin/mpicc.mpich
RUN sudo sed -i "s/ -ffat-lto-objects//g" /usr/bin/mpifort.mpich
RUN sudo sed -i "s/ -fallow-invalid-boz//g" /usr/bin/mpifort.mpich
RUN sudo sed -i "s/ -fallow-argument-mismatch//g" /usr/bin/mpifort.mpich

RUN sudo useradd -m -s /bin/bash -G sudo serac
WORKDIR "/home/serac"
USER serac

RUN git clone --recursive --branch $branch --single-branch --depth 1 https://github.com/LLNL/serac.git serac_repo

# Build/install TPLs via spack and then remove the temporary build directory on success
WORKDIR "/home/serac/serac_repo"
RUN python3 ./scripts/uberenv/uberenv.py --spack-env-file=./scripts/spack/configs/docker/ubuntu24/spack.yaml \
                                                          --project-json=.uberenv_config.json \
                                                          --spec="$spec" --prefix=../serac_tpls -k \
    && rm -rf ../serac_tpls/build_stage ../serac_tpls/spack

RUN mkdir -p ../export_hostconfig
RUN cp *.cmake ../export_hostconfig

# Make sure the new hostconfig worked
# Note: having high job slots causes build log to disappear and job to fail
RUN python3 config-build.py -hc *.cmake -bp build -DBUILD_SHARED_LIBS=ON && cd build && make -j4 VERBOSE=1 && make -j4 test && cd /home/serac && rm -rf serac_repo
