FROM ghcr.io/llnl/radiuss:clang-19-ubuntu-24.04
LABEL maintainer="bramwell1@llnl.gov"
ARG branch=develop

ENV spec="%clang_19"

WORKDIR /opt
COPY ./scripts/docker/setup-ubuntu.sh /opt/scripts
RUN ./scripts/setup-docker.sh

USER serac
WORKDIR /home/serac
RUN git clone --recursive --branch $branch --single-branch --depth 1 https://github.com/LLNL/serac.git serac_repo
RUN ./serac_repo/scripts/docker/setup-serac.sh
