FROM ghcr.io/llnl/radiuss:gcc-14-ubuntu-24.04
LABEL maintainer="bramwell1@llnl.gov"
ARG branch=develop

ENV spec="%gcc_14"

COPY ./scripts/docker /home/scripts
RUN /home/scripts/setup-docker.sh

USER serac
WORKDIR /home/serac
RUN git clone --recursive --branch $branch --single-branch --depth 1 https://github.com/LLNL/serac.git serac_repo
RUN ./serac_repo/scripts/docker/setup-serac.sh
