FROM ghcr.io/llnl/radiuss:clang-19-ubuntu-24.04
LABEL maintainer="bramwell1@llnl.gov"
ARG branch=develop
ENV spec="%clang_19"

SHELL ["/bin/bash", "-c"]
RUN sudo apt-get update -y
RUN sudo apt-get install gettext gfortran-$(gcc -dumpversion) libopenblas-dev \
                         lsb-release lua5.2 lua5.2-dev mpich ssh -fy

# Install enzyme-related packages
RUN if [[ "$spec" != *~enzyme* ]]; then \
      sudo apt-get install llvm-19-dev libzstd-dev libclang-19-dev; \
    fi

# Install devtool-related packages
# NOTE: Skipping this can significantly save disk space
RUN if [[ "$spec" != *~devtools* ]]; then \
      sudo apt-get install graphviz python3-sphinx texlive-full -fy; \
      sudo wget https://github.com/doxygen/doxygen/releases/download/Release_1_9_8/doxygen-1.9.8.linux.bin.tar.gz; \
      sudo tar -xf doxygen-1.9.8.linux.bin.tar.gz; \
      cd doxygen-1.9.8 && sudo make && sudo make install && doxygen --version; \
    fi

# Remove flags from mpich
RUN sudo sed -i "s/ -flto=auto//g" /usr/bin/mpicxx.mpich
RUN sudo sed -i "s/ -flto=auto//g" /usr/bin/mpicc.mpich
RUN sudo sed -i "s/ -flto=auto//g" /usr/bin/mpifort.mpich
RUN sudo sed -i "s/ -ffat-lto-objects//g" /usr/bin/mpicxx.mpich
RUN sudo sed -i "s/ -ffat-lto-objects//g" /usr/bin/mpicc.mpich
RUN sudo sed -i "s/ -ffat-lto-objects//g" /usr/bin/mpifort.mpich
RUN sudo sed -i "s/ -fallow-invalid-boz//g" /usr/bin/mpifort.mpich
RUN sudo sed -i "s/ -fallow-argument-mismatch//g" /usr/bin/mpifort.mpich

RUN sudo useradd -m -s /bin/bash -G sudo serac
WORKDIR "/home/serac"
USER serac

RUN git clone --recursive --branch $branch --single-branch --depth 1 https://github.com/LLNL/serac.git serac_repo

RUN ./serac_repo/scripts/docker/setup-serac.sh
