name: Docker TPL build

# Manually triggered
on:
  workflow_dispatch:
    # No input required

jobs:
  build_images:
    runs-on: ubuntu-latest
    name: Docker TPL build
    strategy:
      matrix:
        dockerfile_suffix: [clang-19, gcc-14] #, cuda-12]
    env:
      REPO: seracllnl/tpls
      HOSTCONFIG_LOC: /home/smith/export_hostconfig
      DOCKERFILE_PREFIX: ./scripts/docker/dockerfile_
    steps:
    - name: Extract branch name
      shell: bash
      run: |
        echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Get dockerfile name
      shell: bash
      run: |
        echo "filename=$(echo ${DOCKERFILE_PREFIX}${{ matrix.dockerfile_suffix }})" >> $GITHUB_OUTPUT
      id: dockerfile_name
    - name: Get dockerhub repo name
      shell: bash
      run: |
        repo_plus_tag=$(echo ${REPO}:${{ matrix.dockerfile_suffix }}_`date "+%m-%d-%y_%Hh-%Mm"`) && export repo_plus_tag
        echo $repo_plus_tag 
        echo "repo_plus_tag=$repo_plus_tag" >> $GITHUB_OUTPUT
        echo "repo_plus_latest=$(echo ${REPO}:${{ matrix.dockerfile_suffix }}_latest)" >> $GITHUB_OUTPUT
      id: repo_name

    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

    - name: Login to DockerHub
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
      with:
        push: true
        tags: ${{ steps.repo_name.outputs.repo_plus_tag }},${{ steps.repo_name.outputs.repo_plus_latest }}
        file: ${{ steps.dockerfile_name.outputs.filename }}
        context: .
        platforms: linux/amd64
        build-args: branch=${{ steps.extract_branch.outputs.branch }}

    - name: Get hostconfig
      run: |
        echo ${{ steps.docker_build.outputs.digest }}
        docker pull ${{ steps.repo_name.outputs.repo_plus_tag }}
        docker create --name extract_hc ${{ steps.repo_name.outputs.repo_plus_tag }}
        mkdir -p extracted_hc
        docker cp extract_hc:${{ env.HOSTCONFIG_LOC }} ./extracted_hc
        docker rm extract_hc
    
    - name: Upload hostconfig
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
      with:
        name: ${{ matrix.dockerfile_suffix }}_hostconfigs
        path: ./extracted_hc/export_hostconfig/*
